/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alexis
 */
public class articulos extends javax.swing.JFrame {
    
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    boolean nuevoRegistro = false;
    long total = 1;
    long posicion = 0;
    inicio pantallainicial = null;
    
    public articulos(Connection c, inicio padre) {
        initComponents();
        this.conn = c;
        crearConexion();
        redimensionar();
        tfid.setEnabled(false);
        tfnombre.setEnabled(false);
        tfprecio.setEnabled(false);
        tfcodigo.setEnabled(false);
        cbgrupo.setEnabled(false);
        this.pantallainicial = padre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbtitulo = new javax.swing.JLabel();
        jpanelprincipal = new javax.swing.JPanel();
        jlidentificador = new javax.swing.JLabel();
        tfid = new javax.swing.JTextField();
        lbnombre = new javax.swing.JLabel();
        lbprecio = new javax.swing.JLabel();
        tfprecio = new javax.swing.JTextField();
        tfnombre = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lbcodigo = new javax.swing.JLabel();
        tfcodigo = new javax.swing.JTextField();
        cbgrupo = new javax.swing.JComboBox();
        lbgrupo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnPrime = new javax.swing.JButton();
        btnAnt = new javax.swing.JButton();
        btnUltim = new javax.swing.JButton();
        btnSig = new javax.swing.JButton();
        lblTot = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblReg = new javax.swing.JLabel();
        lbrgactual = new javax.swing.JLabel();
        lbtotal = new javax.swing.JLabel();
        jbtablaarticulos = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lbtitulo.setBackground(new java.awt.Color(204, 204, 255));
        lbtitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtitulo.setText("MANTENIMIENTO ARTICULOS");
        lbtitulo.setOpaque(true);

        jlidentificador.setText("Identificador");

        lbnombre.setText("Nombre");

        lbprecio.setText("Precio");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lbcodigo.setText("Codigo");

        lbgrupo.setText("Grupo");

        javax.swing.GroupLayout jpanelprincipalLayout = new javax.swing.GroupLayout(jpanelprincipal);
        jpanelprincipal.setLayout(jpanelprincipalLayout);
        jpanelprincipalLayout.setHorizontalGroup(
            jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelprincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlidentificador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbprecio)
                    .addComponent(lbcodigo)
                    .addComponent(lbgrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanelprincipalLayout.createSequentialGroup()
                        .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfprecio)
                            .addComponent(tfnombre)
                            .addComponent(tfid)
                            .addComponent(tfcodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanelprincipalLayout.setVerticalGroup(
            jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelprincipalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelprincipalLayout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit))
                    .addGroup(jpanelprincipalLayout.createSequentialGroup()
                        .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlidentificador)
                            .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbprecio))))
                .addGap(18, 18, 18)
                .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbcodigo)
                    .addComponent(tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbgrupo)
                    .addComponent(cbgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnPrime.setText("|<");
        btnPrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeActionPerformed(evt);
            }
        });

        btnAnt.setText("<<");
        btnAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntActionPerformed(evt);
            }
        });

        btnUltim.setText(">|");
        btnUltim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimActionPerformed(evt);
            }
        });

        btnSig.setText(">>");
        btnSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigActionPerformed(evt);
            }
        });

        lblTot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTot.setText("Tot. registros");
        lblTot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnOk.setText("ACEPTAR");
        btnOk.setEnabled(false);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReg.setText("Reg. actual");
        lblReg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbrgactual.setText("jLabel2");

        lbtotal.setText("jLabel2");

        jbtablaarticulos.setText("Modo Tabla");
        jbtablaarticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtablaarticulosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPrime, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTot, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(lblReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbrgactual)
                    .addComponent(lbtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtablaarticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSig, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUltim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrime)
                    .addComponent(btnAnt)
                    .addComponent(btnUltim)
                    .addComponent(btnSig)
                    .addComponent(lblReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbrgactual))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel)
                    .addComponent(lblTot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtablaarticulos)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpanelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbtitulo)
                .addGap(18, 18, 18)
                .addComponent(jpanelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        nuevoRegistro = true;
        try {
            rs.last();
            long id;
            id = Integer.valueOf(rs.getString("id"));
            tfid.setText(String.valueOf(id + 1));
            rs.moveToInsertRow();
            
            tfnombre.setText("");
            tfprecio.setText("");
            tfcodigo.setText("");
            cbgrupo.setSelectedIndex(0);
            
            botoneraEdicionActivada(false);
            botoneraNavegacionActivada(false);
            tfnombre.requestFocus();
            tfnombre.setEnabled(true);
            tfprecio.setEnabled(true);
            tfcodigo.setEnabled(true);
            cbgrupo.setEnabled(true);
            
            botoneraAccionActivada(true);
            
        } catch (SQLException e) {
            mostrarError(e.getMessage());
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        try {
            if (hayRegistros()) {
                String[] buttons = {"Si", "No"};
                
                int rc = JOptionPane.showOptionDialog(null, "Realmente desea borrar el registro con ID = [" + rs.getLong(1) + "]?",
                        "Confirmation", JOptionPane.WARNING_MESSAGE, 0, null, buttons, buttons[1]);
                
                if (rc == 0) {
                    //borramos_el_Registro;
                    System.out.println("reg actual a borrar" + rs.getRow());
                    rs.deleteRow();
                    if (rs.isBeforeFirst()) {
                        rs.first();
                    }
                    lbrgactual.setText(String.valueOf(rs.getRow()));
                    total = total - 1;
                    lbtotal.setText(String.valueOf(total));
                    //else rs.absolute(r);
                    mostrarDatos(rs);
                }
            }
        } catch (SQLException e) {
            mostrarError(e.getMessage());
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            if (hayRegistros()) {
                nuevoRegistro = false;
                botoneraEdicionActivada(false);
                botoneraNavegacionActivada(false);
                tfnombre.requestFocus();
                tfnombre.setEnabled(true);
                tfprecio.setEnabled(true);
                tfcodigo.setEnabled(true);
                cbgrupo.setEnabled(true);
                botoneraAccionActivada(true);
            }
        } catch (SQLException ex) {
            mostrarError(ex.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void jbtablaarticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtablaarticulosActionPerformed
        try {
            rs.beforeFirst();
            new tabla_articulos(this, true, rs,conn).setVisible(true);
            rs.first();
            mostrarDatos(rs);
            lbrgactual.setText(String.valueOf(rs.getRow()));
        } catch (SQLException ex) {
            Logger.getLogger(MantClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jbtablaarticulosActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try {
            rs.cancelRowUpdates(); //  cancelamos_las_modificaciones;

            tfnombre.setEnabled(false);
            tfprecio.setEnabled(false);
            tfcodigo.setEnabled(false);
            cbgrupo.setEnabled(false);
            cbgrupo.setSelectedIndex(0);
            nuevoRegistro = false;
            lbrgactual.setText(String.valueOf(rs.getRow()));
            
            botoneraAccionActivada(false);
            botoneraNavegacionActivada(true);
            botoneraEdicionActivada(true);
            rs.first();
            mostrarDatos(rs);
           
        } catch (SQLException e) {
            mostrarError(e.getMessage());
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        try {
            // actualizamos_el_campo_nombre_con_el_valor_del_componente_jTextFieldNombre;
            rs.updateString(2, tfnombre.getText());
            // actualizamos_el_campo_direccion_con_el_valor_del_componente_jTextFieldDireccion;
            rs.updateString(3, tfprecio.getText());
            
            rs.updateString(4, tfcodigo.getText());
            String[] iddesc = String.valueOf(cbgrupo.getSelectedItem()).split("-");
            for (int i = 0; i < iddesc.length; i++) {
                System.out.println("array " + iddesc[i]);
            }
            rs.updateString(5, iddesc[0]);
            
            if (nuevoRegistro) {
                // La accion viene por nuevo registro: insertamos_la_fila;
                rs.insertRow();
                // nos_movemos_al_ultimo_Registro;
                rs.last();
                total = rs.getRow();
                lbtotal.setText(String.valueOf(total));
                tfnombre.setEnabled(false);
                tfprecio.setEnabled(false);
                tfcodigo.setEnabled(false);
                cbgrupo.setEnabled(false);
                btnBorrar.setEnabled(true);
                btnEdit.setEnabled(true);
                lbrgactual.setText(String.valueOf(rs.getRow()));
                
            } else {
                //La accion viene por modificacion : actualizamos_el_registro;
                rs.updateRow();
                btnNuevo.setEnabled(true);
                btnBorrar.setEnabled(true);
            }
            nuevoRegistro = false;
            botoneraAccionActivada(false);
            botoneraNavegacionActivada(true);
            botoneraEdicionActivada(true);
            tfnombre.setEnabled(false);
            tfprecio.setEnabled(false);
            tfcodigo.setEnabled(false);
            cbgrupo.setEnabled(false);
            mostrarDatos(rs);
            
        } catch (SQLException e) {
            mostrarError(e.getMessage());
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigActionPerformed
        try {
            rs.next();
            mostrarDatos(rs);
            
            lbrgactual.setText(String.valueOf(rs.getRow()));
        } catch (SQLException e) {
            mostrarError(e.getMessage());
        }
    }//GEN-LAST:event_btnSigActionPerformed

    private void btnUltimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimActionPerformed
        try {
            rs.last();
            mostrarDatos(rs);
            lbrgactual.setText(String.valueOf(rs.getRow()));
        } catch (SQLException e) {
            mostrarError(e.getMessage());
        }
    }//GEN-LAST:event_btnUltimActionPerformed

    private void btnAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntActionPerformed
        try {
            rs.previous();
            mostrarDatos(rs);
            lbrgactual.setText(String.valueOf(rs.getRow()));
        } catch (SQLException e) {
            mostrarError(e.getMessage());
        }
    }//GEN-LAST:event_btnAntActionPerformed

    private void btnPrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeActionPerformed
        try {
            rs.first();
            mostrarDatos(rs);
            lbrgactual.setText(String.valueOf(rs.getRow()));
        } catch (SQLException e) {
            mostrarError(e.getMessage());
        }
    }//GEN-LAST:event_btnPrimeActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            rs.close();
            stmt.close();
            this.setVisible(false);
            pantallainicial.setVisible(true);
        } catch (SQLException e) {
            mostrarError(e.getMessage());
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnt;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnPrime;
    private javax.swing.JButton btnSig;
    private javax.swing.JButton btnUltim;
    private javax.swing.JComboBox cbgrupo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtablaarticulos;
    private javax.swing.JLabel jlidentificador;
    private javax.swing.JPanel jpanelprincipal;
    private javax.swing.JLabel lbcodigo;
    private javax.swing.JLabel lbgrupo;
    private javax.swing.JLabel lblReg;
    private javax.swing.JLabel lblTot;
    private javax.swing.JLabel lbnombre;
    private javax.swing.JLabel lbprecio;
    private javax.swing.JLabel lbrgactual;
    private javax.swing.JLabel lbtitulo;
    private javax.swing.JLabel lbtotal;
    private javax.swing.JTextField tfcodigo;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tfnombre;
    private javax.swing.JTextField tfprecio;
    // End of variables declaration//GEN-END:variables

    private void crearConexion() {
        try {
            
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            cargarcombo();
            String sql = "select * from articulos";
            rs = stmt.executeQuery(sql);
            System.out.println(rs);
            if (rs.first()) {
                mostrarDatos(rs);
            }
            rs.last();
            total = rs.getRow();
            lbtotal.setText(String.valueOf(total));
            rs.first();
            lbrgactual.setText(String.valueOf(rs.getRow()));
            
        } catch (SQLException sqle) {
            mostrarError(sqle.getMessage());
        }
    }
    
    private void mostrarDatos(ResultSet rs) throws SQLException {
        System.out.println("Mostrando..." + rs.getRow());
        if (rs.getRow() > 0) {
            tfid.setText(rs.getLong(1) + "");
            tfnombre.setText(rs.getString(2));
            tfprecio.setText(String.valueOf(rs.getFloat(3)));
            tfcodigo.setText(rs.getString(4));
            //forma rudimentaria para mostrar el item correcto este bucle pasa por todos los elementos del combo box y compara
            // si contiene o no el numero que tenemos en la base de datos puesto que trabaja con equals compara el id tal cual esta
            for (int i = 0; i < cbgrupo.getItemCount(); i++) {
                cbgrupo.setSelectedIndex(i);
                String palabra = String.valueOf(cbgrupo.getSelectedItem());
                String[] iddesc = palabra.split("-");
                if (iddesc[0].equals(String.valueOf(rs.getInt(5)))) {
                    cbgrupo.setSelectedItem(i);
                    break;
                }
            }
            
        } else {
            tfid.setText("");
            tfnombre.setText("");
            tfprecio.setText("");
            tfcodigo.setText("");
            cbgrupo.setSelectedItem(1);
        }
        btnPrime.setEnabled(!rs.isFirst());
        btnAnt.setEnabled(!rs.isFirst());
        btnUltim.setEnabled(!rs.isLast());
        btnSig.setEnabled(!rs.isLast());
        
    }
    
    private void mostrarError(String msg) {
        System.out.println(msg);
        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    private void cargarcombo() throws SQLException {
        String sql = "SELECT * FROM empresa_ad.grupos;";
        rs = stmt.executeQuery(sql);
        
        while (rs.next()) {
            String gr = rs.getLong(1) + "-" + rs.getString(2);
            cbgrupo.addItem(gr);
        }
    }
    
    private void botoneraAccionActivada(boolean estado) {
        btnOk.setEnabled(estado);
        btnCancel.setEnabled(estado);
    }
    
    private void botoneraNavegacionActivada(boolean estado) {
        btnPrime.setEnabled(estado);
        btnAnt.setEnabled(estado);
        btnSig.setEnabled(estado);
        btnUltim.setEnabled(estado);
    }
    
    private void botoneraEdicionActivada(boolean estado) {
        btnNuevo.setEnabled(estado);
        btnBorrar.setEnabled(estado);
        btnEdit.setEnabled(estado);
    }
    
    private boolean hayRegistros() throws SQLException {
        int r = rs.getRow();
        if (!rs.first()) {
            System.out.println("Resultset vacío");
            return false;
        } else {
            System.out.println("Resultset con datos");
            rs.absolute(r);
            return true;
        }
    }
    
    private void redimensionar() {
        
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int ancho = 2 * d.width / 3;
        int alto = d.height / 2;
        this.setLocationRelativeTo(this);
        d = Toolkit.getDefaultToolkit().getScreenSize();
        ancho = 2 * d.width / 6;
        alto = d.height / 4;
        this.setMaximumSize(new Dimension(ancho, alto));
        this.setMinimumSize(new Dimension(ancho, alto));
        this.pack();
        
    }
    
}
