/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;

/**
 *
 * @author alexis
 */
public class form_consulta_articulos1_dialog extends javax.swing.JDialog {

    /**
     * Creates new form form_consulta_articulos1_dialog
     */
    Statement stmt;
    Connection conn;
    JTextArea sqlconsulta;
    ResultSet rs;
    PreparedStatement sqlprepared;

    public form_consulta_articulos1_dialog(java.awt.Frame parent, boolean modal, Connection conn, JTextArea sqlconsulta) {
        super(parent, modal);
        this.conn = conn;
        this.sqlconsulta = sqlconsulta;
        initComponents();
        cargarconexion();
        cargarcombos();
        redimensionar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbreinicio = new javax.swing.JButton();
        jbconsulta = new javax.swing.JButton();
        jldesdehastaid = new javax.swing.JLabel();
        jltitulo = new javax.swing.JLabel();
        jciddesde = new javax.swing.JComboBox();
        jcidhasta = new javax.swing.JComboBox();
        jldesdehastaprecio = new javax.swing.JLabel();
        jcpreciodesde = new javax.swing.JComboBox();
        jcpreciohasta = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jcnombre = new javax.swing.JComboBox();
        lbgrupo = new javax.swing.JLabel();
        jcgrupodesde = new javax.swing.JComboBox();
        jcgrupohasta = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbreinicio.setText("Reiniciar valores por defecto");
        jbreinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbreinicioActionPerformed(evt);
            }
        });

        jbconsulta.setText("Consultar");
        jbconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbconsultaActionPerformed(evt);
            }
        });

        jldesdehastaid.setText("Desde/Hasta ID");

        jltitulo.setBackground(new java.awt.Color(204, 204, 255));
        jltitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltitulo.setText("Criterios de busqueda de Articulos");
        jltitulo.setOpaque(true);

        jldesdehastaprecio.setText("Desde/Hasta Precio");

        jLabel1.setText("Nombre :");

        lbgrupo.setText("Desde/Hasta Grupo ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jltitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbreinicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jldesdehastaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jldesdehastaprecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jcpreciodesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcpreciohasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jciddesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcidhasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(lbgrupo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jcgrupodesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcgrupohasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jcnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jltitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jldesdehastaid)
                    .addComponent(jciddesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcidhasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jldesdehastaprecio)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcpreciodesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcpreciohasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbgrupo)
                    .addComponent(jcgrupodesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcgrupohasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbconsulta)
                    .addComponent(jbreinicio))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbreinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbreinicioActionPerformed
        valoresdef();
    }//GEN-LAST:event_jbreinicioActionPerformed

    private void jbconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbconsultaActionPerformed
        ponerdatossql();

        String s = sqlprepared.toString();
        String[] separado = s.split(" ");
        s = "";
        for (int i = 1; i < separado.length; i++) {

            s = s + " " + separado[i];
        }

        sqlconsulta.setText(s);
        dispose();
    }//GEN-LAST:event_jbconsultaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbconsulta;
    private javax.swing.JButton jbreinicio;
    private javax.swing.JComboBox jcgrupodesde;
    private javax.swing.JComboBox jcgrupohasta;
    private javax.swing.JComboBox jciddesde;
    private javax.swing.JComboBox jcidhasta;
    private javax.swing.JComboBox jcnombre;
    private javax.swing.JComboBox jcpreciodesde;
    private javax.swing.JComboBox jcpreciohasta;
    private javax.swing.JLabel jldesdehastaid;
    private javax.swing.JLabel jldesdehastaprecio;
    private javax.swing.JLabel jltitulo;
    private javax.swing.JLabel lbgrupo;
    // End of variables declaration//GEN-END:variables

    public void valoresdef() {

        jciddesde.setSelectedIndex(0);
        jcidhasta.setSelectedIndex(jcidhasta.getItemCount() - 1);
        jcpreciodesde.setSelectedIndex(0);
        jcpreciohasta.setSelectedIndex(jcpreciohasta.getItemCount() - 1);
        
        jcgrupodesde.setSelectedIndex(0);
        jcgrupohasta.setSelectedIndex(jcgrupohasta.getItemCount() - 1);
        jcnombre.setSelectedIndex(0);

    }

    private void cargarcombos() {

        try {
            String sql = "select id FROM articulos Order by id";
            rs = stmt.executeQuery(sql);
            while (rs.next()) {
                jciddesde.addItem(rs.getLong(1));
                jcidhasta.addItem(rs.getLong(1));
            }
            sql = "select precio FROM articulos Order by precio";
            rs = stmt.executeQuery(sql);
            while (rs.next()) {
                jcpreciodesde.addItem(rs.getLong(1));
                jcpreciohasta.addItem(rs.getLong(1));
            }
            

            sql = "select nombre FROM articulos ";
            rs = stmt.executeQuery(sql);
            while (rs.next()) {
                jcnombre.addItem(rs.getString(1));
            }
            sql = "select id FROM grupos order by id ";
            rs = stmt.executeQuery(sql);
            while (rs.next()) {
                jcgrupodesde.addItem(rs.getLong(1));
                jcgrupohasta.addItem(rs.getLong(1));
            }

            valoresdef();
        } catch (SQLException ex) {
            Logger.getLogger(form_consulta_articulos1_dialog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void cargarconexion() {
        try {
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            sqlprepared = conn.prepareStatement("select * from articulos "
                    + "where (id between ? and ?) "
                    + "and (precio between ? and ?) "
                    + "and (grupo between ? and ?) and (nombre like ?)");
        } catch (SQLException ex) {
            Logger.getLogger(form_consulta_articulos1_dialog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void ponerdatossql() {

        try {

            sqlprepared.setLong(1, Long.parseLong(String.valueOf(jciddesde.getSelectedItem())));
            sqlprepared.setLong(2, Long.parseLong(String.valueOf(jcidhasta.getSelectedItem())));
            sqlprepared.setFloat(3, Float.parseFloat(String.valueOf(jcpreciodesde.getSelectedItem())));
            sqlprepared.setFloat(4, Float.parseFloat(String.valueOf(jcpreciohasta.getSelectedItem())));
            sqlprepared.setLong(5, Long.parseLong(String.valueOf(jcgrupodesde.getSelectedItem())));
            sqlprepared.setLong(6, Long.parseLong(String.valueOf(jcgrupohasta.getSelectedItem())));
            sqlprepared.setString(7, String.valueOf(jcnombre.getSelectedItem()));

        } catch (SQLException ex) {
            Logger.getLogger(form_consulta_articulos1_dialog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void redimensionar() {
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int ancho = d.width;
        int alto = d.height;
        this.setLocationRelativeTo(this);
        d = Toolkit.getDefaultToolkit().getScreenSize();
        ancho = 2 * d.width / 6;
        alto = d.height / 4;
        this.setMaximumSize(new Dimension(ancho, alto));
        this.setMinimumSize(new Dimension(ancho, alto));
        this.pack();
    }

}
