/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo;

import com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vesprada
 */
public class FormularioDeConsultas extends javax.swing.JFrame {

    /**
     * Creates new form FormularioDeConsultas
     */
    DatabaseMetaData dbmd = null;
    Connection conn;
    inicio pantallainicial;
    ResultSet rs;
    Statement stmt = null;
    String sql;
    DefaultTableModel m = null;
    form_consulta_facturas1_dialog opciones;
    form_consulta_articulos1_dialog opciones2;
    PreparedStatement sqlprepared;
    boolean inicio = false;

    public FormularioDeConsultas(Connection conn, inicio padre) {
        try {
            initComponents();
            this.conn = conn;
            opciones = new form_consulta_facturas1_dialog(this, true, this.conn, txtareaconsultas);
            opciones2 = new form_consulta_articulos1_dialog(this, true, this.conn, txtareaconsultas);
            redimensionar();
            this.pantallainicial = padre;
            dbmd = conn.getMetaData();
            crearConexion();
            infoTablas(dbmd);

        } catch (SQLException ex) {
            Logger.getLogger(FormularioDeConsultas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbelije = new javax.swing.JLabel();
        jctablas = new javax.swing.JComboBox();
        jbconsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtconsultas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareaconsultas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de consultas ");
        jLabel1.setOpaque(true);

        lbelije.setText("Elije una tabla:");

        jctablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jctablasActionPerformed(evt);
            }
        });

        jbconsultar.setText("CONSULTAR");
        jbconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbconsultarActionPerformed(evt);
            }
        });

        jtconsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtconsultas);

        txtareaconsultas.setColumns(20);
        txtareaconsultas.setLineWrap(true);
        txtareaconsultas.setRows(5);
        jScrollPane2.setViewportView(txtareaconsultas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbelije)
                            .addComponent(jctablas, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2))
                    .addComponent(jbconsultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbelije)
                        .addGap(18, 18, 18)
                        .addComponent(jctablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbconsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jctablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jctablasActionPerformed

        txtareaconsultas.setText("SELECT * from " + jctablas.getSelectedItem());

        if (inicio) {
            switch ((String) jctablas.getSelectedItem()) {
                case "facturas":
                    opciones.valoresdef();
                    opciones.setVisible(true);
                    break;
                case "articulos":
                    opciones2.valoresdef();
                    opciones2.setVisible(true);
            }
        } else {
            inicio = true;
        }
    }//GEN-LAST:event_jctablasActionPerformed

    private void jbconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbconsultarActionPerformed

        sql = String.valueOf(txtareaconsultas.getText());
        CargarEnTabla(sql);


    }//GEN-LAST:event_jbconsultarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    
            
            this.setVisible(false);
            pantallainicial.setVisible(true);
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public void infoTablas(DatabaseMetaData dbmd) throws SQLException {

        String patron = "%";
        String tipos[] = new String[3];
        String nombretabla;
        tipos[0] = "TABLE";
        tipos[1] = "VIEW";

        ResultSet tablas = dbmd.getTables(null, null, patron, tipos);
        while (tablas.next()) {
            nombretabla = tablas.getString("TABLE_NAME");

            if (!nombretabla.equals("lineas_factura")) {
                jctablas.addItem(nombretabla);
            }
        }

    }

    private void crearConexion() {

        try {
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

        } catch (SQLException ex) {
            Logger.getLogger(FormularioDeConsultas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void CargarEnTabla(String sql) {
        try {

            sqlprepared = conn.prepareStatement(txtareaconsultas.getText());
            rs = sqlprepared.executeQuery();

            String[] col = new String[rs.getMetaData().getColumnCount()];

            for (int i = 0; i < col.length; i++) {

                col[i] = rs.getMetaData().getColumnName(i + 1);
            }

            m = new DefaultTableModel(null, col);
            String[] lineas = new String[col.length];
            while (rs.next()) {
                for (int i = 0; i < lineas.length; i++) {
                    lineas[i] = rs.getString(i + 1);
                }
                m.addRow(lineas);
            }
            jtconsultas.setModel(m);

        } catch (MySQLSyntaxErrorException es) {

            JOptionPane.showMessageDialog(this, "La Sentencia No Es Correcta", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {

            Logger.getLogger(FormularioDeConsultas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbconsultar;
    private javax.swing.JComboBox jctablas;
    private javax.swing.JTable jtconsultas;
    private javax.swing.JLabel lbelije;
    private javax.swing.JTextArea txtareaconsultas;
    // End of variables declaration//GEN-END:variables

    private void redimensionar() {
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int ancho = 2 * d.width / 3;
        int alto = d.height / 2;
        this.setLocationRelativeTo(this);
        d = Toolkit.getDefaultToolkit().getScreenSize();
        ancho = 2 * d.width / 6;
        alto = d.height / 4;
        this.setMaximumSize(new Dimension(ancho, alto));
        this.setMinimumSize(new Dimension(ancho, alto));
        this.pack();
    }
}
