/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alexis
 */
public class inicio extends javax.swing.JDialog {

    /**
     * Creates new form inicio
     *
     * @param parent
     * @param modal
     */
    public static Connection conn = null;

    public inicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        redimensionar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jbclientes = new javax.swing.JButton();
        jbarticulos = new javax.swing.JButton();
        jbfacturas = new javax.swing.JButton();
        jbformconsulta = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbclientes.setText("CLIENTES");
        jbclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbclientesActionPerformed(evt);
            }
        });

        jbarticulos.setText("ARTICULOS");
        jbarticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbarticulosActionPerformed(evt);
            }
        });

        jbfacturas.setText("FACTURAS");
        jbfacturas.setMaximumSize(new java.awt.Dimension(97, 24));
        jbfacturas.setMinimumSize(new java.awt.Dimension(97, 24));
        jbfacturas.setPreferredSize(new java.awt.Dimension(97, 24));
        jbfacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbfacturasActionPerformed(evt);
            }
        });

        jbformconsulta.setText("FORMULARIO DE CONSULTA");
        jbformconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbformconsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbfacturas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbclientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbarticulos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbformconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbarticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbfacturas, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbformconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbclientesActionPerformed
        if (conn != null) {
            new MantClientes(conn, this).setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Conexion no establecida", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbclientesActionPerformed

    private void jbarticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbarticulosActionPerformed
        if (conn != null) {
            new articulos(conn, this).setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Conexion no establecida", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbarticulosActionPerformed

    private void jbfacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbfacturasActionPerformed
        if (conn != null) {
            new facturas(conn, this).setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Conexion no establecida", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbfacturasActionPerformed

    private void jbformconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbformconsultaActionPerformed

        if (conn != null) {
            new FormularioDeConsultas(conn, this).setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Conexion no establecida", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jbformconsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                inicio dialog = new inicio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);

            }

        });
        conexion();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jbarticulos;
    private javax.swing.JButton jbclientes;
    private javax.swing.JButton jbfacturas;
    private javax.swing.JButton jbformconsulta;
    // End of variables declaration//GEN-END:variables

    private void redimensionar() {
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int ancho = 2 * d.width / 3;
        int alto = d.height / 2;
        this.setLocationRelativeTo(this);

        this.pack();
    }

    public static void conexion() {
        try {
            String driver = "com.mysql.jdbc.Driver";
            Class.forName(driver).newInstance();
            System.out.println("Driver " + driver + " Registrado correctamente");
            System.out.println("Conectando con la Base de datos...");
            String jdbcUrl = "jdbc:mysql://localhost:3306/empresa_ad";
            conn = DriverManager.getConnection(jdbcUrl, "dam", "1234");
            System.out.println("Conexión establecida con la Base de datos...");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("pericolospalotees");
        }
    }
}
