/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alexis
 */
public class lineas_dialog extends javax.swing.JDialog {

    ResultSet rs;
    Connection conn;
    Statement stmt = null;
    facturas facturas = null;
    boolean editaroanadir = true;//true es aadir una nueva linea
    boolean actprecio = false;//no actualizara el precio del articulo
    PreparedStatement pstmtanadirlineas = null;
    PreparedStatement pstmteditarfacturas = null;

    public lineas_dialog(java.awt.Frame parent, boolean modal, Connection c) throws SQLException {
        super(parent, modal);
        initComponents();
        this.conn = c;
        this.facturas = (ejemplo.facturas) parent;
        stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        pstmtanadirlineas = conn.prepareStatement("INSERT INTO `empresa_ad`.`lineas_factura`(`linea`,`factura`,`articulo`,`cantidad`,`importe`)VALUES(?,?,?,?,?);");
        pstmteditarfacturas = conn.prepareStatement("UPDATE `empresa_ad`.`lineas_factura` SET `articulo` = ?,`cantidad` = ?,`importe` = ? WHERE `linea` = ? AND `factura` = ? ");      
        cargarcombos();
        redimensionar();
        

        jtfimporte.setEnabled(false);
        jbguardar.setEnabled(false);
        jtflinea.setEditable(false);
        jtffactura.setEditable(false);
        jtfcantidad.setEditable(true);
        

    }

    public void ponerdatoanadir(long linea, String factura) {
        jtflinea.setText(String.valueOf(linea));
        jtffactura.setText(factura);
        cbarticulos.setSelectedIndex(0);

    }

    public void ponerdatoseditar(String linea, String factura, String idarti,String cantidad, String importe) {
        jtflinea.setText(linea);
        jtffactura.setText(factura);
        jtfcantidad.setText(cantidad);
        jtfimporte.setText(importe);

        for (int i = 0; i < cbarticulos.getItemCount(); i++) {
            cbarticulos.setSelectedIndex(i);
            String palabra = String.valueOf(cbarticulos.getSelectedItem());
            String[] iddesc = palabra.split("-");
            if (iddesc[0].equals(idarti)) {
                cbarticulos.setSelectedItem(i);
                break;
            }
        }
        editaroanadir = false;
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelprincipal = new javax.swing.JPanel();
        lblinea = new javax.swing.JLabel();
        lbfactura = new javax.swing.JLabel();
        lbarticulo = new javax.swing.JLabel();
        lbcantidad = new javax.swing.JLabel();
        lbimporte = new javax.swing.JLabel();
        jtflinea = new javax.swing.JTextField();
        jtffactura = new javax.swing.JTextField();
        cbarticulos = new javax.swing.JComboBox();
        lbprecioarticulo = new javax.swing.JLabel();
        jtfcantidad = new javax.swing.JTextField();
        jtfimporte = new javax.swing.JTextField();
        jbguardar = new javax.swing.JButton();
        lbeuros = new javax.swing.JLabel();
        jbcalcularimporte = new javax.swing.JButton();
        lbtitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblinea.setText("Linea");

        lbfactura.setText("Factura");

        lbarticulo.setText("Articulo");

        lbcantidad.setText("Cantidad");

        lbimporte.setText("Importe");

        cbarticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbarticulosActionPerformed(evt);
            }
        });

        lbprecioarticulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbprecioarticulo.setText("Precio.art");

        jtfcantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfcantidadFocusLost(evt);
            }
        });
        jtfcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfcantidadActionPerformed(evt);
            }
        });

        jtfimporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfimporteActionPerformed(evt);
            }
        });

        jbguardar.setText("Guardar");
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });

        lbeuros.setText("Euros");

        jbcalcularimporte.setText("Calcular Importe");
        jbcalcularimporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcalcularimporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelprincipalLayout = new javax.swing.GroupLayout(jpanelprincipal);
        jpanelprincipal.setLayout(jpanelprincipalLayout);
        jpanelprincipalLayout.setHorizontalGroup(
            jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelprincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelprincipalLayout.createSequentialGroup()
                        .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblinea)
                            .addComponent(lbfactura)
                            .addComponent(lbarticulo))
                        .addGap(27, 27, 27)
                        .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtflinea, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jtffactura)
                            .addComponent(cbarticulos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lbprecioarticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbeuros)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpanelprincipalLayout.createSequentialGroup()
                        .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbcantidad)
                            .addComponent(lbimporte))
                        .addGap(21, 21, 21)
                        .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelprincipalLayout.createSequentialGroup()
                                .addComponent(jtfcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbcalcularimporte)
                                .addGap(0, 156, Short.MAX_VALUE))
                            .addComponent(jtfimporte))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelprincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbguardar)
                .addGap(249, 249, 249))
        );
        jpanelprincipalLayout.setVerticalGroup(
            jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelprincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinea)
                    .addComponent(jtflinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbfactura)
                    .addComponent(jtffactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbarticulo)
                    .addComponent(cbarticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbprecioarticulo)
                    .addComponent(lbeuros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcantidad)
                    .addComponent(jtfcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbcalcularimporte))
                .addGap(18, 18, 18)
                .addGroup(jpanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbimporte)
                    .addComponent(jtfimporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbguardar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        lbtitulo.setBackground(new java.awt.Color(204, 204, 255));
        lbtitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtitulo.setText("MANTENIMIENTO LINEAS DE FACTURA");
        lbtitulo.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jpanelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpanelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbarticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbarticulosActionPerformed
        if (actprecio) {
            try {
                String[] id = String.valueOf(cbarticulos.getSelectedItem()).split("-");

                String sql = "select precio from articulos where id=" + id[0];
                rs = stmt.executeQuery(sql);
                rs.next();
                lbprecioarticulo.setText(rs.getLong(1) + "");
                jtfcantidad.setEnabled(true);
            } catch (SQLException ex) {
                Logger.getLogger(lineas_dialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_cbarticulosActionPerformed

    private void jtfimporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfimporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfimporteActionPerformed

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed
        try {

            if (editaroanadir) {
                pstmtanadirlineas.setInt(1, Integer.parseInt(jtflinea.getText()));
                pstmtanadirlineas.setInt(2, Integer.parseInt(jtffactura.getText()));
                String[] iddesc = String.valueOf(cbarticulos.getSelectedItem()).split("-");
                
                pstmtanadirlineas.setInt(3, Integer.parseInt(iddesc[0]));
                pstmtanadirlineas.setInt(4, Integer.parseInt(jtfcantidad.getText()));
                pstmtanadirlineas.setInt(5, Integer.parseInt(jtfimporte.getText()));
                pstmtanadirlineas.executeUpdate();
                jtflinea.setText(String.valueOf(Integer.parseInt(jtflinea.getText()) + 1));
                jtfcantidad.setText("");
                jtfimporte.setText("");
                JOptionPane.showMessageDialog(this,"REGISTRO CORRECTAMENTE");

            } else {
                
                String[] iddesc = String.valueOf(cbarticulos.getSelectedItem()).split("-");
                
               
                
                String sql="UPDATE `empresa_ad`.`lineas_factura` SET `articulo` ="+Integer.parseInt(iddesc[0])+",`cantidad` = "+Integer.parseInt(jtfcantidad.getText())+",`importe` = "+Integer.parseInt(jtfimporte.getText())+" WHERE `linea` = "+Integer.parseInt(jtflinea.getText())+" AND `factura` = "+Integer.parseInt(jtffactura.getText());
                stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                stmt.executeUpdate(sql);
                
               JOptionPane.showMessageDialog(this,"REGISTRO EDITADO CORRECTAMENTE");
                
                this.dispose();
                
               
                
                
                
                
                
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(lineas_dialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbguardarActionPerformed

    private void jtfcantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfcantidadFocusLost

         

    }//GEN-LAST:event_jtfcantidadFocusLost

    private void jtfcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfcantidadActionPerformed

    private void jbcalcularimporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcalcularimporteActionPerformed
      if (jtfcantidad.getText().length() != 0 && this.isNumeric(jtfcantidad.getText())) {

            jtfimporte.setText(String.valueOf(Integer.parseInt(lbprecioarticulo.getText()) * Integer.parseInt(jtfcantidad.getText())));

            jbguardar.setEnabled(true);
        }else{
        JOptionPane.showMessageDialog(this,
    "ERROR: CAMPO CANTIDAD VACIO O CON SIMBOLOS NO ACEPTADOS (solo aptos numeros)",
    "ERROR",JOptionPane.ERROR_MESSAGE);
         jbguardar.setEnabled(false);
        jtfcantidad.requestFocus(true);
        }
    }//GEN-LAST:event_jbcalcularimporteActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarcombos() {
        try {

            String sql = "select id,nombre from articulos";
            rs = stmt.executeQuery(sql);
            while (rs.next()) {
                String gr = rs.getLong(1) + "-" + rs.getString(2);
                cbarticulos.addItem(gr);
            }

        } catch (SQLException ex) {
            Logger.getLogger(lineas_dialog.class.getName()).log(Level.SEVERE, null, ex);

        }
        actprecio = true;
    }

    

    private void redimensionar() {

        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int ancho = 2 * d.width / 3;
        int alto = d.height / 2;
        this.setLocationRelativeTo(this);
        d = Toolkit.getDefaultToolkit().getScreenSize();
        ancho = 2 * d.width / 6;
        alto = d.height / 4;
        this.setMaximumSize(new Dimension(ancho, alto));
        this.setMinimumSize(new Dimension(ancho, alto));
        this.pack();

    }

    private static boolean isNumeric(String cadena){
	try {
		Integer.parseInt(cadena);
		return true;
	} catch (NumberFormatException nfe){
		return false;
	}
}
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbarticulos;
    private javax.swing.JButton jbcalcularimporte;
    private javax.swing.JButton jbguardar;
    private javax.swing.JPanel jpanelprincipal;
    private javax.swing.JTextField jtfcantidad;
    private javax.swing.JTextField jtffactura;
    private javax.swing.JTextField jtfimporte;
    private javax.swing.JTextField jtflinea;
    private javax.swing.JLabel lbarticulo;
    private javax.swing.JLabel lbcantidad;
    private javax.swing.JLabel lbeuros;
    private javax.swing.JLabel lbfactura;
    private javax.swing.JLabel lbimporte;
    private javax.swing.JLabel lblinea;
    private javax.swing.JLabel lbprecioarticulo;
    private javax.swing.JLabel lbtitulo;
    // End of variables declaration//GEN-END:variables
}
